=== DDC-NDRS/systerel_S2OPC/schemas/s2opc_clientserver_users_config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="S2OPC_Users" type="S2OPC_UsersType"/>
  <xs:complexType name="UserAuthorizationType">
    <xs:attribute type="xs:boolean" name="read" default="false"/>
    <xs:attribute type="xs:boolean" name="write" default="false"/>
    <xs:attribute type="xs:boolean" name="execute" default="false"/>
    <xs:attribute type="xs:boolean" name="addnode" default="false"/>
    <xs:attribute type="xs:boolean" name="receive_events" default="false"/>
  </xs:complexType>
  <xs:complexType name="AnonymousType">
    <xs:sequence>
          <xs:element type="UserAuthorizationType" name="UserAuthorization"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UserPasswordType">
    <xs:sequence>
          <xs:element type="UserAuthorizationType" name="UserAuthorization"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="user" use="required"/>
    <xs:attribute type="xs:string" name="hash" use="required"/>
    <xs:attribute type="xs:string" name="salt" use="required"/>
    <!-- TODO: Add base64 encoding feature (see ticket #1057)
    <xs:attribute type="xs:string" name="base64" use="optional"/>
    -->
  </xs:complexType>
  <xs:complexType name="UserPasswordConfigurationType">
    <xs:sequence>
      <xs:element type="UserPasswordType" name="UserPassword" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="hash_iteration_count" use="required"/>
    <xs:attribute type="xs:string" name="hash_length" use="required"/>
    <xs:attribute type="xs:string" name="salt_length" use="required"/>
  </xs:complexType>
  <xs:complexType name="PublicKeyInfrastructureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
        <xs:attribute type="xs:boolean" name="read" default="false"/>
        <xs:attribute type="xs:boolean" name="write" default="false"/>
        <xs:attribute type="xs:boolean" name="execute" default="false"/>
        <xs:attribute type="xs:boolean" name="addnode" default="false"/>
        <xs:attribute type="xs:boolean" name="receive_events" default="false">
          <xs:annotation>
            <xs:documentation>Default certificate authorization for accepted certificate, evaluated as trustworthy according to the PKI</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UserCertificateRightsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="path" use="required"/>
        <xs:attribute type="xs:boolean" name="read" default="false"/>
        <xs:attribute type="xs:boolean" name="write" default="false"/>
        <xs:attribute type="xs:boolean" name="execute" default="false"/>
        <xs:attribute type="xs:boolean" name="addnode" default="false"/>
        <xs:attribute type="xs:boolean" name="receive_events" default="false">
          <xs:annotation>
              <xs:documentation>Explicitly certificate authorization for accepted certificate, evaluated as trustworthy according to the PKI </xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="UserCertificatesType">
    <xs:sequence>
      <xs:element type="PublicKeyInfrastructureType" name="PublicKeyInfrastructure" minOccurs="1" maxOccurs="1"/>
      <xs:element type="UserCertificateRightsType" name="UserCertificateRights" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="S2OPC_UsersType">
    <xs:sequence>
      <xs:element type="AnonymousType" name="Anonymous" minOccurs="0"/>
      <xs:element type="UserPasswordConfigurationType" name="UserPasswordConfiguration" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UserCertificatesType" name="UserCertificates" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== DDC-NDRS/systerel_S2OPC/tests/ClientServer/data/config/S2OPC_Users_Tests_Roles_Config.xml
<?xml version='1.0' encoding='utf-8'?>
<S2OPC_Users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="s2opc_clientserver_users_config.xsd">
  <Anonymous>
    <!-- Anonymous -->
    <UserAuthorization write="true" read="true" execute="true" addnode="true"/>
  </Anonymous>
  <UserPasswordConfiguration hash_iteration_count="10000" hash_length="32" salt_length="16">
    <!-- "user1" pwd=password -->
    <UserPassword user="user1" hash="55c6b4d28fffb9ff1bc8951560eb8d07665aa41a25cd7687a2588c7381814195" salt="c64fd08487e0dc2706583c4416a2e17f">
      <UserAuthorization write="true" read="true" execute="true" addnode="true"/>
    </UserPassword>
    <!-- "me" pwd=1234 -->
    <UserPassword user="me" hash="847d892ffaccb9822d417866f9d491389b29134b3c73c3a429ac95c627f9d40a" salt="17faf802f81c2503d3043042e79004b4">
      <UserAuthorization write="true" read="true" execute="true" addnode="true"/>
    </UserPassword>
  </UserPasswordConfiguration>
  <UserCertificates>
    <PublicKeyInfrastructure path="./S2OPC_Users_PKI" write="true" read="true" execute="true" addnode="true"/>
    <UserCertificateRights path="user_public/user_2k_cert.der" write="true" read="true" execute="true" addnode="true"/>
  </UserCertificates>
</S2OPC_Users>
